import { ContractError, ERROR_CODES, freezeJsonValue } from '../core/index.ts';
import type { JsonObject } from '../core/types.ts';
import { requireEntityId, requireRevision, requireSequence, type PresetRecord, type QueueItemRecord, type QueueRecord, type TemplateRecord } from '../persistence/types.ts';
import { requireRunSnapshot } from '../runs/model.ts';
import { isRunTerminal } from '../runs/types.ts';
import { requireSettingsWriteInput } from '../settings/model.ts';
import { PORTABLE_FORMAT_VERSION, PORTABLE_PRODUCT, type ImportMode, type PortableEnvelope, type PortableHistoryRun, type PortableQueue, type PortableRunEvent, type PortableSettings } from './types.ts';

function object(value: unknown, label: string): Record<string, unknown> { if (value === null || Array.isArray(value) || typeof value !== 'object') throw new ContractError(ERROR_CODES.invalidMessage, `${label} must be an object`); return value as Record<string, unknown>; }
function array(value: unknown, label: string): unknown[] { if (!Array.isArray(value)) throw new ContractError(ERROR_CODES.invalidMessage, `${label} must be an array`); return value; }
function text(value: unknown, label: string, max = 256): string { if (typeof value !== 'string' || value.length < 1 || value.length > max) throw new ContractError(ERROR_CODES.invalidMessage, `${label} must be 1..${max} characters`); return value; }
function timestamp(value: unknown, label: string): string { const v=text(value,label,64); if (Number.isNaN(Date.parse(v))) throw new ContractError(ERROR_CODES.invalidMessage, `${label} must be an ISO timestamp`); return v; }
function exactKeys(raw: Record<string, unknown>, allowed: readonly string[], label: string): void { const set=new Set(allowed); for(const key of Object.keys(raw)) if(!set.has(key)) throw new ContractError(ERROR_CODES.invalidMessage, `${label} contains unsupported field ${key}`); }
function schema1(raw: Record<string, unknown>, label: string): void { if (raw.schemaVersion !== 1) throw new ContractError(ERROR_CODES.unsupportedSchema, `${label} schemaVersion must be 1`); }

function templateRecord(value: unknown): TemplateRecord { const r=object(value,'template'); exactKeys(r,['schemaVersion','id','revision','name','body','enabled','createdAt','updatedAt'],'template'); schema1(r,'template'); requireEntityId(r.id,'template id'); requireRevision(r.revision,'template revision'); text(r.name,'template name',120); if(typeof r.body!=='string'||r.body.length<1||r.body.length>65536)throw new ContractError(ERROR_CODES.invalidMessage,'template body must be 1..65536 characters'); if(typeof r.enabled!=='boolean')throw new ContractError(ERROR_CODES.invalidMessage,'template enabled must be boolean'); timestamp(r.createdAt,'template createdAt');timestamp(r.updatedAt,'template updatedAt'); return freezeJsonValue(r as unknown as TemplateRecord); }
function presetRecord(value: unknown): PresetRecord { const r=object(value,'preset'); exactKeys(r,['schemaVersion','id','revision','name','mode','templateId','queueId','iterationCount','delaySeconds','autoContinue','autoScroll','preventDiscard','createdAt','updatedAt'],'preset'); schema1(r,'preset'); requireEntityId(r.id,'preset id');requireRevision(r.revision,'preset revision');text(r.name,'preset name',120);if(r.mode!=='repeat'&&r.mode!=='queue')throw new ContractError(ERROR_CODES.invalidMessage,'preset mode must be repeat|queue'); if(r.mode==='repeat'){requireEntityId(r.templateId,'preset template id');if(r.queueId!==null)throw new ContractError(ERROR_CODES.invalidMessage,'repeat preset queueId must be null');}else{requireEntityId(r.queueId,'preset queue id');if(r.templateId!==null)throw new ContractError(ERROR_CODES.invalidMessage,'queue preset templateId must be null');} if(!Number.isSafeInteger(r.iterationCount)||(r.iterationCount as number)<1||(r.iterationCount as number)>10000)throw new ContractError(ERROR_CODES.invalidMessage,'preset iterationCount invalid'); if(!Number.isSafeInteger(r.delaySeconds)||(r.delaySeconds as number)<5||(r.delaySeconds as number)>3600)throw new ContractError(ERROR_CODES.invalidMessage,'preset delaySeconds invalid'); for(const k of ['autoContinue','autoScroll','preventDiscard'])if(typeof r[k]!=='boolean')throw new ContractError(ERROR_CODES.invalidMessage,`preset ${k} must be boolean`);timestamp(r.createdAt,'preset createdAt');timestamp(r.updatedAt,'preset updatedAt');return freezeJsonValue(r as unknown as PresetRecord); }
function queueRecord(value: unknown): QueueRecord { const r=object(value,'queue');exactKeys(r,['schemaVersion','id','revision','name','createdAt','updatedAt'],'queue');schema1(r,'queue');requireEntityId(r.id,'queue id');requireRevision(r.revision,'queue revision');text(r.name,'queue name',120);timestamp(r.createdAt,'queue createdAt');timestamp(r.updatedAt,'queue updatedAt');return freezeJsonValue(r as unknown as QueueRecord); }
function queueItemRecord(value: unknown, queueId: string): QueueItemRecord { const r=object(value,'queue item');exactKeys(r,['schemaVersion','id','queueId','position','message','templateId','enabled','delayAfterSeconds','createdAt','updatedAt'],'queue item');schema1(r,'queue item');requireEntityId(r.id,'queue item id');if(r.queueId!==queueId)throw new ContractError(ERROR_CODES.invalidMessage,'queue item queueId mismatch');requireSequence(r.position,'queue item position');const hasMessage=typeof r.message==='string'&&r.message.length>0;const hasTemplate=r.templateId!==null;if(hasMessage===hasTemplate)throw new ContractError(ERROR_CODES.invalidMessage,'queue item requires exactly one message or templateId');if(hasMessage&&(r.message as string).length>65536)throw new ContractError(ERROR_CODES.invalidMessage,'queue item message too long');if(hasTemplate)requireEntityId(r.templateId,'queue item template id');if(typeof r.enabled!=='boolean')throw new ContractError(ERROR_CODES.invalidMessage,'queue item enabled must be boolean');if(r.delayAfterSeconds!==null&&(!Number.isSafeInteger(r.delayAfterSeconds)||(r.delayAfterSeconds as number)<5||(r.delayAfterSeconds as number)>3600))throw new ContractError(ERROR_CODES.invalidMessage,'queue item delay invalid');timestamp(r.createdAt,'queue item createdAt');timestamp(r.updatedAt,'queue item updatedAt');return freezeJsonValue(r as unknown as QueueItemRecord); }
function portableQueue(value: unknown): PortableQueue { const r=object(value,'portable queue');exactKeys(r,['queue','items'],'portable queue');const queue=queueRecord(r.queue);const items=array(r.items,'queue items').map(v=>queueItemRecord(v,queue.id)).sort((a,b)=>a.position-b.position);const positions=new Set<number>();for(const item of items){if(positions.has(item.position))throw new ContractError(ERROR_CODES.invalidMessage,'queue item positions must be unique');positions.add(item.position);}return freezeJsonValue({queue,items}); }
function settings(value: unknown): PortableSettings { const values=requireSettingsWriteInput(object(value,'portable settings')); return freezeJsonValue(values as PortableSettings); }
function portableEvent(value: unknown, runId: string): PortableRunEvent { const r=object(value,'run event');exactKeys(r,['id','sequence','eventType','payload','occurredAt'],'run event');requireEntityId(r.id,'run event id');requireSequence(r.sequence,'run event sequence');text(r.eventType,'run event type',64);if(r.payload===null||Array.isArray(r.payload)||typeof r.payload!=='object')throw new ContractError(ERROR_CODES.invalidMessage,'run event payload must be an object');timestamp(r.occurredAt,'run event occurredAt');return freezeJsonValue({id:r.id as string,sequence:r.sequence as number,eventType:r.eventType as string,payload:r.payload as JsonObject,occurredAt:r.occurredAt as string}); }
function historyRun(value: unknown): PortableHistoryRun { const r=object(value,'history run');exactKeys(r,['run','events'],'history run');const run=requireRunSnapshot(r.run);if(!isRunTerminal(run.lifecycleState))throw new ContractError(ERROR_CODES.invalidMessage,'full backup history may contain terminal runs only');const events=array(r.events,'history events').map(v=>portableEvent(v,run.id)).sort((a,b)=>a.sequence-b.sequence);const sequences=new Set<number>();for(const event of events){if(sequences.has(event.sequence))throw new ContractError(ERROR_CODES.invalidMessage,'history event sequences must be unique');sequences.add(event.sequence);}return freezeJsonValue({run,events}); }

export function requireImportMode(value: unknown): ImportMode { if(value!=='merge'&&value!=='replace_imported'&&value!=='replace_all')throw new ContractError(ERROR_CODES.invalidMessage,'import mode must be merge|replace_imported|replace_all');return value; }

export function requirePortableEnvelope(value: unknown): PortableEnvelope {
  const r=object(value,'portable envelope');exactKeys(r,['product','formatVersion','kind','appVersion','exportedAt','data'],'portable envelope');
  if(r.product!==PORTABLE_PRODUCT)throw new ContractError(ERROR_CODES.unsupportedSchema,`unsupported portable product: ${String(r.product)}`);
  const adapter=PORTABLE_IMPORT_ADAPTERS.get(Number(r.formatVersion));if(adapter===undefined)throw new ContractError(ERROR_CODES.unsupportedSchema,`unsupported portable formatVersion: ${String(r.formatVersion)}`);
  return adapter(r);
}

function adaptV1(r:Record<string,unknown>):PortableEnvelope{
  if(r.formatVersion!==PORTABLE_FORMAT_VERSION)throw new ContractError(ERROR_CODES.unsupportedSchema,'portable formatVersion must be 1');if(r.kind!=='configuration'&&r.kind!=='full_backup')throw new ContractError(ERROR_CODES.invalidMessage,'portable kind must be configuration|full_backup');const dataRaw=object(r.data,'portable data');exactKeys(dataRaw,r.kind==='full_backup'?['templates','presets','queues','settings','history']:['templates','presets','queues','settings'],'portable data');
  const templates=array(dataRaw.templates,'templates').map(templateRecord);const presets=array(dataRaw.presets,'presets').map(presetRecord);const queues=array(dataRaw.queues,'queues').map(portableQueue);const portableSettings=settings(dataRaw.settings);const history=r.kind==='full_backup'?array(dataRaw.history,'history').map(historyRun):undefined;
  const ids=(label:string,values:readonly{readonly id:string}[])=>{const seen=new Set<string>();for(const item of values){if(seen.has(item.id))throw new ContractError(ERROR_CODES.invalidMessage,`${label} ids must be unique`);seen.add(item.id);}};ids('template',templates);ids('preset',presets);ids('queue',queues.map(q=>q.queue));ids('history run',(history??[]).map(h=>h.run));const allItems=queues.flatMap(q=>q.items);ids('queue item',allItems);ids('history event',(history??[]).flatMap(h=>h.events));
  return freezeJsonValue({product:PORTABLE_PRODUCT,formatVersion:PORTABLE_FORMAT_VERSION,kind:r.kind,appVersion:text(r.appVersion,'appVersion',64),exportedAt:timestamp(r.exportedAt,'exportedAt'),data:{templates,presets,queues,settings:portableSettings,...(history===undefined?{}:{history})}} as PortableEnvelope);
}

export type PortableImportAdapter=(raw:Record<string,unknown>)=>PortableEnvelope;
export const PORTABLE_IMPORT_ADAPTERS:ReadonlyMap<number,PortableImportAdapter>=new Map([[1,adaptV1]]);
