import { ContractError, ERROR_CODES, freezeJsonValue } from '../core/index.ts';
import type { JsonObject } from '../core/types.ts';
import type { ApplicationRepositories, RepositoryTransaction } from '../persistence/repositories.ts';
import type { PresetRecord, QueueItemRecord, QueueRecord, RunEventRecord, RunRecord, TemplateRecord } from '../persistence/types.ts';
import { requireRunSnapshot } from '../runs/model.ts';
import { isRunTerminal, type DurableRunSnapshot } from '../runs/types.ts';
import type { SettingsService } from '../settings/service.ts';
import type { SettingsSnapshot } from '../settings/types.ts';
import { PORTABLE_FORMAT_VERSION, PORTABLE_PRODUCT, PORTABLE_SCHEMA_VERSION, type ImportApplyResult, type ImportMode, type ImportPreview, type PortableCounts, type PortableEnvelope, type PortableHistoryRun, type PortableQueue } from './types.ts';
import { requireImportMode, requirePortableEnvelope } from './model.ts';

interface CurrentState { templates:TemplateRecord[];presets:PresetRecord[];queues:QueueRecord[];items:QueueItemRecord[];runs:RunRecord[];events:RunEventRecord[];settings:SettingsSnapshot; }
const idMap=<T extends{readonly id:string}>(rows:readonly T[])=>new Map(rows.map(r=>[r.id,r]));
const sorted=<T extends{readonly id:string}>(rows:readonly T[])=>[...rows].sort((a,b)=>a.id.localeCompare(b.id));
function counts(e:PortableEnvelope):PortableCounts{return freezeJsonValue({templates:e.data.templates.length,presets:e.data.presets.length,queues:e.data.queues.length,queueItems:e.data.queues.reduce((n,q)=>n+q.items.length,0),historyRuns:e.data.history?.length??0,historyEvents:e.data.history?.reduce((n,h)=>n+h.events.length,0)??0});}
function settingsValues(s:SettingsSnapshot){return{defaultPresetId:s.defaultPresetId,defaultDelaySeconds:s.defaultDelaySeconds,defaultAutoContinue:s.defaultAutoContinue,defaultAutoScroll:s.defaultAutoScroll,defaultPreventDiscard:s.defaultPreventDiscard,recoveryPolicy:s.recoveryPolicy,historyLimit:s.historyLimit};}
function token(e:PortableEnvelope,mode:ImportMode,s:CurrentState):string{return JSON.stringify({source:{product:e.product,formatVersion:e.formatVersion,kind:e.kind,appVersion:e.appVersion,exportedAt:e.exportedAt},mode,settingsRevision:s.settings.revision,templates:sorted(s.templates).map(x=>[x.id,x.revision]),presets:sorted(s.presets).map(x=>[x.id,x.revision]),queues:sorted(s.queues).map(x=>[x.id,x.revision]),items:sorted(s.items).map(x=>[x.id,x.queueId,x.position,x.updatedAt]),runs:sorted(s.runs).map(x=>[x.id,x.updatedAt]),events:sorted(s.events).map(x=>[x.id,x.runId,x.sequence])});}
function runRecord(run:DurableRunSnapshot):RunRecord{return freezeJsonValue({schemaVersion:1,id:run.id,logicalVersion:run.schemaVersion,state:run,createdAt:run.createdAt,updatedAt:run.updatedAt});}
function eventRecord(runId:string,event:PortableHistoryRun['events'][number]):RunEventRecord{return freezeJsonValue({schemaVersion:1,id:event.id,runId,sequence:event.sequence,eventType:event.eventType,payload:event.payload,occurredAt:event.occurredAt});}

function validateReferences(e:PortableEnvelope,current:CurrentState,mode:ImportMode):void{
  const t=idMap(mode==='replace_all'?e.data.templates:[...current.templates,...(mode==='replace_imported'?e.data.templates:e.data.templates.filter(x=>!idMap(current.templates).has(x.id)))]);
  const q=idMap(mode==='replace_all'?e.data.queues.map(x=>x.queue):[...current.queues,...(mode==='replace_imported'?e.data.queues.map(x=>x.queue):e.data.queues.map(x=>x.queue).filter(x=>!idMap(current.queues).has(x.id)))]);
  const p=idMap(mode==='replace_all'?e.data.presets:[...current.presets,...(mode==='replace_imported'?e.data.presets:e.data.presets.filter(x=>!idMap(current.presets).has(x.id)))]);
  for(const queue of e.data.queues)for(const item of queue.items){if(item.templateId!==null){const template=t.get(item.templateId);if(template===undefined)throw new ContractError(ERROR_CODES.invalidMessage,'imported queue references a missing template');if(item.enabled&&!template.enabled)throw new ContractError(ERROR_CODES.invalidMessage,'enabled imported queue item references a disabled template');}}
  for(const preset of e.data.presets){if(preset.mode==='repeat'&&!t.has(preset.templateId!))throw new ContractError(ERROR_CODES.invalidMessage,'imported preset references a missing template');if(preset.mode==='queue'&&!q.has(preset.queueId!))throw new ContractError(ERROR_CODES.invalidMessage,'imported preset references a missing queue');}
  if(e.data.settings.defaultPresetId!==null&&!p.has(e.data.settings.defaultPresetId))throw new ContractError(ERROR_CODES.invalidMessage,'imported settings defaultPresetId does not exist after import');
  if(e.data.history){const currentRuns=idMap(current.runs);const currentEvents=idMap(current.events);for(const h of e.data.history){const existing=currentRuns.get(h.run.id);if(existing!==undefined&&!isRunTerminal(requireRunSnapshot(existing.state).lifecycleState))throw new ContractError(ERROR_CODES.staleRequest,'full backup conflicts with an active/nonterminal run id');for(const ev of h.events){const old=currentEvents.get(ev.id);if(old!==undefined&&old.runId!==h.run.id)throw new ContractError(ERROR_CODES.staleRequest,'full backup event id conflicts with another run');}}}
}

export class PortabilityService{
  readonly #repositories:ApplicationRepositories;readonly #settings:SettingsService;readonly #appVersion:string;readonly #now:()=>string;
  constructor(repositories:ApplicationRepositories,settings:SettingsService,appVersion:string,now:()=>string=()=>new Date().toISOString()){this.#repositories=repositories;this.#settings=settings;this.#appVersion=appVersion;this.#now=now;}
  async export(kind:'configuration'|'full_backup'):Promise<PortableEnvelope>{const current=await this.#current();const queueItemsByQueue=new Map<string,QueueItemRecord[]>();for(const item of current.items){const list=queueItemsByQueue.get(item.queueId)??[];list.push(item);queueItemsByQueue.set(item.queueId,list);}const queues:PortableQueue[]=current.queues.map(queue=>freezeJsonValue({queue,items:(queueItemsByQueue.get(queue.id)??[]).sort((a,b)=>a.position-b.position)}));let history:PortableHistoryRun[]|undefined;if(kind==='full_backup'){history=[];for(const row of current.runs){const run=requireRunSnapshot(row.state);if(!isRunTerminal(run.lifecycleState))continue;const events=current.events.filter(e=>e.runId===run.id).sort((a,b)=>a.sequence-b.sequence).map(e=>freezeJsonValue({id:e.id,sequence:e.sequence,eventType:e.eventType,payload:e.payload,occurredAt:e.occurredAt}));history.push(freezeJsonValue({run,events}));}}
    return freezeJsonValue({product:PORTABLE_PRODUCT,formatVersion:PORTABLE_FORMAT_VERSION,kind,appVersion:this.#appVersion,exportedAt:this.#now(),data:{templates:current.templates,presets:current.presets,queues,settings:settingsValues(current.settings),...(history===undefined?{}:{history})}} as PortableEnvelope);
  }
  async preview(raw:unknown,rawMode:unknown):Promise<ImportPreview>{const envelope=requirePortableEnvelope(raw);const mode=requireImportMode(rawMode);const current=await this.#current();validateReferences(envelope,current,mode);const c=counts(envelope);const conflicts=freezeJsonValue({templates:envelope.data.templates.filter(x=>current.templates.some(y=>y.id===x.id)).length,presets:envelope.data.presets.filter(x=>current.presets.some(y=>y.id===x.id)).length,queues:envelope.data.queues.filter(x=>current.queues.some(y=>y.id===x.queue.id)).length,historyRuns:(envelope.data.history??[]).filter(x=>current.runs.some(y=>y.id===x.run.id)).length,historyEvents:(envelope.data.history??[]).flatMap(x=>x.events).filter(x=>current.events.some(y=>y.id===x.id)).length});const warnings:string[]=[];if(envelope.kind==='full_backup')warnings.push('Full backup includes terminal run metadata and event payloads. Current terminal prompt bodies are compacted; imported legacy backups are normalized on read. Treat backups as sensitive.');if(mode==='merge')warnings.push('Merge keeps existing records when stable IDs collide.');if(mode==='replace_all')warnings.push('Replace all replaces configuration and, for full backups, terminal history; active runs are preserved.');return freezeJsonValue({schemaVersion:PORTABLE_SCHEMA_VERSION,product:PORTABLE_PRODUCT,formatVersion:envelope.formatVersion,kind:envelope.kind,sourceAppVersion:envelope.appVersion,exportedAt:envelope.exportedAt,mode,counts:c,conflicts,planFingerprint:token(envelope,mode,current),warnings});}
  async apply(raw:unknown,rawMode:unknown,planFingerprint:unknown):Promise<ImportApplyResult>{const envelope=requirePortableEnvelope(raw);const mode=requireImportMode(rawMode);if(typeof planFingerprint!=='string'||planFingerprint.length<1)throw new ContractError(ERROR_CODES.invalidMessage,'planFingerprint is required');const current=await this.#current();validateReferences(envelope,current,mode);if(token(envelope,mode,current)!==planFingerprint)throw new ContractError(ERROR_CODES.staleRequest,'local data changed after import preview; preview again');const oldSettings=current.settings;const nextSettings=await this.#settings.update(oldSettings.revision,envelope.data.settings);try{await this.#repositories.write(['templates','presets','queues','queueItems','runs','runEvents'],async tx=>await this.#applyDb(tx,envelope,mode));}catch(error){await this.#settings.restore(oldSettings);throw error;}return freezeJsonValue({schemaVersion:PORTABLE_SCHEMA_VERSION,mode,kind:envelope.kind,applied:counts(envelope)});}
  async #current():Promise<CurrentState>{const settings=await this.#settings.get();return await this.#repositories.readonly(['templates','presets','queues','queueItems','runs','runEvents'],async tx=>({templates:await tx.repository('templates').list(),presets:await tx.repository('presets').list(),queues:await tx.repository('queues').list(),items:await tx.repository('queueItems').list(),runs:await tx.repository('runs').list(),events:await tx.repository('runEvents').list(),settings}));}
  async #applyDb(tx:RepositoryTransaction,e:PortableEnvelope,mode:ImportMode):Promise<void>{const templates=tx.repository('templates'),presets=tx.repository('presets'),queues=tx.repository('queues'),items=tx.repository('queueItems'),runs=tx.repository('runs'),events=tx.repository('runEvents');const existingTemplates=idMap(await templates.list()),existingPresets=idMap(await presets.list()),existingQueues=idMap(await queues.list());if(mode==='replace_all'){for(const row of existingTemplates.values())await templates.delete(row.id);for(const row of existingPresets.values())await presets.delete(row.id);for(const row of existingQueues.values())await queues.delete(row.id);for(const row of await items.list())await items.delete(row.id);}for(const row of e.data.templates){if(mode==='merge'&&existingTemplates.has(row.id))continue;await templates.put(row);}for(const row of e.data.presets){if(mode==='merge'&&existingPresets.has(row.id))continue;await presets.put(row);}for(const portable of e.data.queues){if(mode==='merge'&&existingQueues.has(portable.queue.id))continue;if(mode==='replace_imported'){for(const item of await items.listByIndex('byQueueId',portable.queue.id))await items.delete(item.id);}await queues.put(portable.queue);for(const item of portable.items)await items.put(item);}if(!e.data.history)return;const existingRuns=idMap(await runs.list());if(mode==='replace_all'){for(const row of existingRuns.values()){const run=requireRunSnapshot(row.state);if(!isRunTerminal(run.lifecycleState))continue;for(const ev of await events.listByIndex('byRunId',run.id))await events.delete(ev.id);await runs.delete(run.id);}}
    for(const h of e.data.history){const existing=existingRuns.get(h.run.id);if(mode==='merge'&&existing!==undefined)continue;if(mode==='replace_imported'&&existing!==undefined){for(const ev of await events.listByIndex('byRunId',h.run.id))await events.delete(ev.id);await runs.delete(h.run.id);}await runs.put(runRecord(h.run));for(const ev of h.events)await events.put(eventRecord(h.run.id,ev));}
  }
}
