import { ContractError, ERROR_CODES, createFailureResponse, createSuccessResponse, requireMessageEnvelope, type RequestEnvelope } from '../core/index.ts';
import type { JsonObject } from '../core/types.ts';
import type { QueueService } from '../queues/service.ts';
import { QUEUE_RUNTIME_OPERATIONS } from '../queues/types.ts';

export type QueueServiceProvider=()=>Promise<QueueService>;
function requireRequest(raw:unknown):RequestEnvelope{const m=requireMessageEnvelope(raw);if(m.kind!=='request')throw new ContractError(ERROR_CODES.invalidMessage,'queue runtime accepts requests only');if(m.target!=='background'||m.source!=='sidepanel')throw new ContractError(ERROR_CODES.invalidMessage,'queue requests must originate from sidepanel and target background');return m;}
function requireOnly(payload:JsonObject,allowed:readonly string[]):void{const extras=Object.keys(payload).filter(k=>!allowed.includes(k));if(extras.length)throw new ContractError(ERROR_CODES.invalidMessage,`unexpected queue payload field: ${extras[0]}`);}
function str(payload:JsonObject,key:string):string{const v=payload[key];if(typeof v!=='string')throw new ContractError(ERROR_CODES.invalidMessage,`${key} is required`);return v;}
export class QueueRuntimeServer{readonly #service:QueueServiceProvider;readonly #onChanged:(()=>void)|undefined;constructor(service:QueueServiceProvider,onChanged?:()=>void){this.#service=service;this.#onChanged=onChanged;}async handle(raw:unknown):Promise<unknown>{let request:RequestEnvelope|undefined;try{request=requireRequest(raw);const p=request.payload;const s=await this.#service();switch(request.operation){case QUEUE_RUNTIME_OPERATIONS.list:if(request.intent!=='query')throw new ContractError(ERROR_CODES.invalidMessage,'queue.list must be a query');requireOnly(p,[]);return createSuccessResponse(request,await s.list());case QUEUE_RUNTIME_OPERATIONS.get:if(request.intent!=='query')throw new ContractError(ERROR_CODES.invalidMessage,'queue.get must be a query');requireOnly(p,['queueId']);return createSuccessResponse(request,await s.get(str(p,'queueId'))??null);case QUEUE_RUNTIME_OPERATIONS.references:if(request.intent!=='query')throw new ContractError(ERROR_CODES.invalidMessage,'queue.references must be a query');requireOnly(p,[]);return createSuccessResponse(request,await s.references());case QUEUE_RUNTIME_OPERATIONS.hydrate:if(request.intent!=='query')throw new ContractError(ERROR_CODES.invalidMessage,'queue.hydrate must be a query');requireOnly(p,['queueId']);return createSuccessResponse(request,await s.hydrate(str(p,'queueId')));case QUEUE_RUNTIME_OPERATIONS.create:{if(request.intent!=='command')throw new ContractError(ERROR_CODES.invalidMessage,'queue.create must be a command');requireOnly(p,['name','items']);const v=await s.create(request.requestId,p);this.#onChanged?.();return createSuccessResponse(request,v);}case QUEUE_RUNTIME_OPERATIONS.update:{if(request.intent!=='command')throw new ContractError(ERROR_CODES.invalidMessage,'queue.update must be a command');requireOnly(p,['queueId','expectedRevision','name','items']);const v=await s.update(str(p,'queueId'),p.expectedRevision,p);this.#onChanged?.();return createSuccessResponse(request,v);}case QUEUE_RUNTIME_OPERATIONS.duplicate:{if(request.intent!=='command')throw new ContractError(ERROR_CODES.invalidMessage,'queue.duplicate must be a command');requireOnly(p,['queueId','expectedRevision','name']);const v=await s.duplicate(str(p,'queueId'),p.expectedRevision,request.requestId,p.name);this.#onChanged?.();return createSuccessResponse(request,v);}case QUEUE_RUNTIME_OPERATIONS.delete:if(request.intent!=='command')throw new ContractError(ERROR_CODES.invalidMessage,'queue.delete must be a command');requireOnly(p,['queueId','expectedRevision']);await s.delete(str(p,'queueId'),p.expectedRevision);this.#onChanged?.();return createSuccessResponse(request,{deleted:true});default:throw new ContractError(ERROR_CODES.unsupportedOperation,`Unsupported queue operation: ${request.operation}`);}}catch(error){if(request!==undefined)return createFailureResponse(request,error);throw error;}}}
