import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
import { ApplicationRepositories, NamespacedChromeStorage, PERSISTENCE_STORES } from '../src/persistence/index.ts';
import { SettingsService, requireSettingsWriteInput } from '../src/settings/index.ts';
import { RunHistoryService } from '../src/history/index.ts';
import { DiagnosticsService } from '../src/diagnostics/index.ts';
import { DurableRunManager, DurableRunRepository } from '../src/runs/index.ts';
import { SettingsRuntimeServer, HistoryRuntimeServer, DiagnosticsRuntimeServer } from '../src/runtime/index.ts';
import { SidePanelDiagnosticsClient, SidePanelHistoryClient, SidePanelSettingsClient, blankSettingsDraft, settingsDraftFrom } from '../src/ui/settings-workspace.ts';

const text=(path)=>readFile(new URL(`../${path}`,import.meta.url),'utf8');
const clone=(v)=>structuredClone(v); const keyFor=(s,v)=>s==='metadata'?v.key:v.id;
function matchesIndex(store,index,value,query){if(query===undefined)return true;if(store==='queueItems'&&index==='byQueueId')return value.queueId===query;if(store==='runEvents'&&index==='byRunId')return value.runId===query;if(store==='runEvents'&&index==='byRunSequence')return Array.isArray(query)&&value.runId===query[0]&&value.sequence===query[1];return value[index==='byUpdatedAt'?'updatedAt':index==='byPosition'?'position':index==='byOccurredAt'?'occurredAt':'id']===query;}
class MemoryDriver{state=new Map(PERSISTENCE_STORES.map(n=>[n,new Map()]));async transaction(stores,mode,work){const before=new Map([...this.state].map(([n,v])=>[n,new Map([...v].map(([k,x])=>[k,clone(x)]))]));const port={store:(name)=>({get:async k=>{const v=this.state.get(name).get(k);return v===undefined?undefined:clone(v)},getAll:async()=>[...this.state.get(name).values()].map(clone),getAllByIndex:async(i,q)=>[...this.state.get(name).values()].filter(v=>matchesIndex(name,i,v,q)).map(clone),put:async v=>{if(mode!=='readwrite')throw Error('readonly');this.state.get(name).set(keyFor(name,v),clone(v))},delete:async k=>{if(mode!=='readwrite')throw Error('readonly');this.state.get(name).delete(k)}})};try{return await work(port)}catch(e){this.state=before;throw e}}close(){}}
class MemoryStorageArea{values={};async get(keys){if(keys==null)return clone(this.values);const list=Array.isArray(keys)?keys:[keys];return Object.fromEntries(list.filter(k=>k in this.values).map(k=>[k,clone(this.values[k])]))}async set(items){Object.assign(this.values,clone(items))}async remove(keys){for(const key of Array.isArray(keys)?keys:[keys])delete this.values[key]}}
function settingsHarness(){const area=new MemoryStorageArea();let tick=0;const service=new SettingsService(new NamespacedChromeStorage(area,'sync'),()=>new Date(Date.parse('2026-08-24T04:00:00+08:00')+tick++*1000).toISOString());return{area,service};}
function repositoriesHarness(){return new ApplicationRepositories(new MemoryDriver())}
async function runHarness(){const repositories=repositoriesHarness();let tick=0;const repo=new DurableRunRepository(repositories,{now:()=>new Date(Date.parse('2026-08-24T04:10:00+08:00')+tick++*1000).toISOString(),id:()=>crypto.randomUUID()});const manager=new DurableRunManager(repo);return{repositories,manager};}

const valid={defaultPresetId:null,defaultDelaySeconds:7,defaultAutoContinue:true,defaultAutoScroll:true,defaultPreventDiscard:true,recoveryPolicy:'resume',historyLimit:100};

test('STEP-13 settings contract validates bounded defaults, recovery policy, history retention, and system appearance authority',()=>{assert.equal(requireSettingsWriteInput(valid).historyLimit,100);assert.throws(()=>requireSettingsWriteInput({...valid,defaultDelaySeconds:4}),/5\.\.3600/);assert.throws(()=>requireSettingsWriteInput({...valid,recoveryPolicy:'magic'}),/resume\|pause/);assert.throws(()=>requireSettingsWriteInput({...valid,historyLimit:251}),/1\.\.250/);});

test('STEP-13 SettingsService persists only sync-safe preferences with revision fencing',async()=>{const{area,service}=settingsHarness();const initial=await service.get();assert.equal(initial.appearance,'system');const next=await service.update(initial.revision,{...valid,defaultDelaySeconds:9,recoveryPolicy:'pause'});assert.equal(next.revision,2);assert.equal(next.defaultDelaySeconds,9);assert.equal(next.recoveryPolicy,'pause');assert.ok(Object.keys(area.values).every(k=>k.startsWith('iterator.sync.')));await assert.rejects(()=>service.update(1,valid),/revision changed/);});

test('STEP-13 Settings runtime and Side Panel client preserve correlated get/update semantics',async()=>{const{service}=settingsHarness();let changed=0;const server=new SettingsRuntimeServer(async()=>service,()=>{changed++});const client=new SidePanelSettingsClient({sendMessage:async req=>await server.handle(req)});const current=await client.get();const draft=settingsDraftFrom(current);draft.historyLimit=25;const next=await client.update(current,draft);assert.equal(next.historyLimit,25);assert.equal(changed,1);assert.equal(blankSettingsDraft().recoveryPolicy,'resume');});

test('STEP-13 bounded history retains newest terminal summaries and never prunes active runs',async()=>{const{repositories,manager}=await runHarness();const ids=[];for(let i=0;i<4;i++){let run=(await manager.create({targetTabId:i+1,targetWindowId:1,commandId:crypto.randomUUID(),messageTemplate:`secret ${i}`,totalIterations:1,delaySeconds:5,autoContinue:true,autoScroll:true,preventDiscard:true})).snapshot;ids.push(run.id);if(i<3)await manager.stop(run.id,run.generation,crypto.randomUUID());}const history=new RunHistoryService(repositories);const before=await history.list(2);assert.equal(before.totalRetained,3);assert.equal(before.entries.length,2);assert.equal(JSON.stringify(before).includes('secret'),false);const pruned=await history.enforceRetention(2);assert.equal(pruned.removedRuns,1);const all=await manager.list();assert.equal(all.some(r=>r.id===ids[3]&&r.lifecycleState==='ready'),true);assert.equal((await history.list(100)).totalRetained,2);});

test('STEP-13 history clear removes terminal runs/events only and runtime client exposes the bounded projection',async()=>{const{repositories,manager}=await runHarness();let stopped=(await manager.create({targetTabId:1,targetWindowId:1,commandId:crypto.randomUUID(),messageTemplate:'private',totalIterations:1,delaySeconds:5,autoContinue:true,autoScroll:true,preventDiscard:true})).snapshot;await manager.stop(stopped.id,stopped.generation,crypto.randomUUID());const active=(await manager.create({targetTabId:2,targetWindowId:1,commandId:crypto.randomUUID(),messageTemplate:'active private',totalIterations:1,delaySeconds:5,autoContinue:true,autoScroll:true,preventDiscard:true})).snapshot;const history=new RunHistoryService(repositories);const{service:settings}=settingsHarness();const server=new HistoryRuntimeServer(async()=>history,async()=>settings);const client=new SidePanelHistoryClient({sendMessage:async req=>await server.handle(req)});assert.equal((await client.list()).entries.length,1);const cleared=await client.clear();assert.equal(cleared.removedRuns,1);assert.equal((await manager.get(active.id)).lifecycleState,'ready');});

test('STEP-13 diagnostics composes adapter required/conditional health with runtime/tab/database/storage/data counts without private payloads',async()=>{const repositories=repositoriesHarness();await repositories.write(['metadata','templates'],async tx=>{await tx.repository('metadata').put({key:'logicalMigrationState',value:{state:'complete',version:2},updatedAt:'2026-08-24T00:00:00Z'});await tx.repository('templates').put({schemaVersion:1,id:'11111111-1111-4111-8111-111111111111',revision:1,name:'T',body:'SECRET BODY',enabled:true,createdAt:'2026-08-24T00:00:00Z',updatedAt:'2026-08-24T00:00:00Z'});});const tabs={schemaVersion:1,revision:1,targets:[{schemaVersion:1,tabId:9,windowId:1,active:true,title:'ChatGPT',url:'https://chatgpt.com/',browserStatus:'complete',lifecycleState:'ready',autoDiscardable:true,contentConnected:true,adapterReady:true,adapterBusy:false,pageAlert:null}],binding:{schemaVersion:1,tabId:9,windowId:1,boundAt:'2026-08-24T00:00:00Z',reason:'explicit'},lastTermination:null};const service=new DiagnosticsService(repositories,{appVersion:'0.0.13',workerStartedAt:'2026-08-24T00:00:00Z',connectedPanels:()=>1,tabs:()=>tabs,runs:async()=>[],adapterDiagnostics:async()=>({schemaVersion:2,status:'ready',capabilities:[{key:'composer',requirement:'required',status:'ready',matchedBy:'#prompt-textarea',count:1},{key:'continue',requirement:'conditional',status:'absent',matchedBy:null,count:0}],pageAlert:null})});const snapshot=await service.snapshot();assert.equal(snapshot.adapter.capabilities[0].requirement,'required');assert.equal(snapshot.adapter.capabilities[1].requirement,'conditional');assert.equal(snapshot.database.physicalDbVersion,1);assert.equal(snapshot.data.templates,1);const serialized=JSON.stringify(snapshot);assert.equal(serialized.includes('SECRET BODY'),false);assert.equal(serialized.includes('composerDraft'),false);assert.match(serialized,/sync/);});

test('STEP-13 diagnostics runtime/client returns privacy-safe projections through background authority',async()=>{const repositories=repositoriesHarness();const service=new DiagnosticsService(repositories,{appVersion:'0.0.13',workerStartedAt:'2026-08-24T00:00:00Z',connectedPanels:()=>2,tabs:()=>({schemaVersion:1,revision:0,targets:[],binding:null,lastTermination:null}),runs:async()=>[],adapterDiagnostics:async()=>{throw Error('not bound')}});const server=new DiagnosticsRuntimeServer(async()=>service);const client=new SidePanelDiagnosticsClient({sendMessage:async req=>await server.handle(req)});const snapshot=await client.get();assert.equal(snapshot.adapter.status,'not_bound');assert.equal(snapshot.runtime.connectedPanels,2);});

test('STEP-13 Settings workspace follows team-standard cards/actions and makes Run defaults explicit without setup-first gating',async()=>{const app=await text('entrypoints/sidepanel/App.vue');for(const marker of ['settings-default-preset','settings-delay','settings-recovery','settings-history-limit','saveSettings','resetSettings','applyRunDefaults','refreshSettingsDiagnostics','clearRunHistory'])assert.match(app,new RegExp(marker));assert.match(app,/activeWorkspace === 'settings'/);assert.match(app,/structured-list/);assert.doesNotMatch(app,/chrome:\/\/theme|--google-|Material Symbols/);});

test('STEP-13 background wiring applies recovery policy, history pruning, isolated invalidations, and existing adapter diagnostics authority',async()=>{const[bg,router,types,client,adapter]=await Promise.all(['entrypoints/background.ts','src/runtime/message-router.ts','src/control-plane/types.ts','src/runs/chatgpt-client.ts','src/chatgpt/adapter.ts'].map(text));assert.match(bg,/settings\.recoveryPolicy === 'pause'/);assert.match(bg,/enforceRetention\(settings\.historyLimit\)/);assert.match(bg,/history_changed/);assert.match(types,/settings_changed/);assert.match(types,/history_changed/);assert.match(router,/SETTINGS_RUNTIME_OPERATIONS/);assert.match(router,/DIAGNOSTICS_RUNTIME_OPERATIONS/);assert.match(router,/HISTORY_RUNTIME_OPERATIONS/);assert.match(client,/CHATGPT_ADAPTER_OPERATIONS\.diagnostics/);assert.match(adapter,/requirement/);});

test('STEP-13 retained boundary keeps physical DB and permissions stable while roadmap ownership advances normally',async()=>{const[versions,config,roadmap]=await Promise.all(['src/persistence/versions.ts','wxt.config.ts','agents/records/roadmaps/ROADMAP-0001--chrome-native-iterator-foundation.md'].map(text));assert.match(versions,/PHYSICAL_DB_VERSION\s*=\s*1/);assert.match(config,/permissions:\s*\[['"]sidePanel['"],\s*['"]storage['"],\s*['"]alarms['"]\]/);assert.match(roadmap,/STEP-14 — Versioned Export, Import/);});
