import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
import { ApplicationRepositories, PERSISTENCE_STORES } from '../src/persistence/index.ts';
import { createSuccessResponse } from '../src/core/index.ts';
import { QueueService, requireQueueWriteInput } from '../src/queues/index.ts';
import { TemplateService } from '../src/templates/index.ts';
import { PresetService } from '../src/presets/index.ts';
import { QueueMessageSource } from '../src/messages/index.ts';
import { DurableRunManager, DurableRunRepository, RepeatRunCoordinator } from '../src/runs/index.ts';
import { QueueRuntimeServer, RunRuntimeServer } from '../src/runtime/index.ts';
import { SidePanelOperationalClient } from '../src/ui/run-workspace.ts';
import { TAB_REGISTRY_SCHEMA_VERSION } from '../src/tabs/index.ts';
import { SidePanelQueueClient, blankQueueDraft, isQueueDraftDirty, isQueueDraftStale, moveQueueItem, queueDraftFrom } from '../src/ui/queue-workspace.ts';
import { runWorkingCopyFromPreset } from '../src/ui/preset-workspace.ts';

const text=(path)=>readFile(new URL(`../${path}`,import.meta.url),'utf8');
const clone=(v)=>structuredClone(v); const keyFor=(s,v)=>s==='metadata'?v.key:v.id;
function matchesIndex(store,index,value,query){if(query===undefined)return true;if(store==='queueItems'&&index==='byQueueId')return value.queueId===query;if(store==='runEvents'&&index==='byRunId')return value.runId===query;if(store==='runEvents'&&index==='byRunSequence')return Array.isArray(query)&&value.runId===query[0]&&value.sequence===query[1];return value[index==='byUpdatedAt'?'updatedAt':index==='byPosition'?'position':index==='byOccurredAt'?'occurredAt':'id']===query;}
class MemoryDriver{state=new Map(PERSISTENCE_STORES.map(n=>[n,new Map()]));async transaction(stores,mode,work){const before=new Map([...this.state].map(([n,v])=>[n,new Map([...v].map(([k,x])=>[k,clone(x)]))]));const port={store:(name)=>({get:async k=>{const v=this.state.get(name).get(k);return v===undefined?undefined:clone(v)},getAll:async()=>[...this.state.get(name).values()].map(clone),getAllByIndex:async(i,q)=>[...this.state.get(name).values()].filter(v=>matchesIndex(name,i,v,q)).map(clone),put:async v=>{if(mode!=='readwrite')throw Error('readonly');this.state.get(name).set(keyFor(name,v),clone(v))},delete:async k=>{if(mode!=='readwrite')throw Error('readonly');this.state.get(name).delete(k)}})};try{return await work(port)}catch(e){this.state=before;throw e}}close(){}}
const ids={queue:'11111111-1111-4111-8111-111111111111',queue2:'22222222-2222-4222-8222-222222222222',template:'33333333-3333-4333-8333-333333333333',preset:'44444444-4444-4444-8444-444444444444',item1:'55555555-5555-4555-8555-555555555555',item2:'66666666-6666-4666-8666-666666666666'};
async function harness(){const driver=new MemoryDriver();const repositories=new ApplicationRepositories(driver);let tick=0;const base=Date.parse('2026-08-24T04:00:00+08:00');const now=()=>new Date(base+tick++*1000).toISOString();const generated=[ids.item1,ids.item2,'77777777-7777-4777-8777-777777777777','88888888-8888-4888-8888-888888888888'];let gi=0;const templates=new TemplateService(repositories,now);const queues=new QueueService(repositories,now,()=>generated[gi++]??crypto.randomUUID());const presets=new PresetService(repositories,now);await templates.create(ids.template,{name:'Template',body:'Template {iteration}/{total}',enabled:true});return{driver,repositories,templates,queues,presets,now};}
const input={name:'Primary',items:[{id:null,message:'Literal {iteration}/{total}',templateId:null,enabled:true,delayAfterSeconds:9},{id:null,message:null,templateId:ids.template,enabled:true,delayAfterSeconds:null}]};

test('STEP-12 queue contract requires ordered executable items with exactly one message source',()=>{assert.equal(requireQueueWriteInput(input).items.length,2);assert.throws(()=>requireQueueWriteInput({name:'Bad',items:[{id:null,message:'x',templateId:ids.template,enabled:true,delayAfterSeconds:null}]}),/exactly one/);assert.throws(()=>requireQueueWriteInput({name:'Bad',items:[{id:null,message:'x',templateId:null,enabled:false,delayAfterSeconds:null}]}),/at least one enabled/);assert.throws(()=>requireQueueWriteInput({name:'Bad',items:[{id:null,message:'x',templateId:null,enabled:true,delayAfterSeconds:4}]}),/5 to 3600/);});

test('STEP-12 QueueService transactionally saves stable item IDs, ordering, revisions, and references',async()=>{const{queues}=await harness();const created=await queues.create(ids.queue,input);assert.equal(created.queue.revision,1);assert.deepEqual(created.items.map(i=>[i.id,i.position]),[[ids.item1,0],[ids.item2,1]]);const draft={name:'Reordered',items:[{id:ids.item2,message:null,templateId:ids.template,enabled:true,delayAfterSeconds:7},{id:ids.item1,message:'Literal moved',templateId:null,enabled:true,delayAfterSeconds:null}]};const updated=await queues.update(ids.queue,1,draft);assert.equal(updated.queue.revision,2);assert.deepEqual(updated.items.map(i=>[i.id,i.position]),[[ids.item2,0],[ids.item1,1]]);await assert.rejects(()=>queues.update(ids.queue,1,draft),/revision changed/);});

test('STEP-12 Queue runtime/client exposes bounded CRUD, hydration, and isolated change notifications', async()=>{const{queues}=await harness();let invalidations=0;const server=new QueueRuntimeServer(async()=>queues,()=>{invalidations++});const client=new SidePanelQueueClient({sendMessage:async req=>await server.handle(req)});const draft=blankQueueDraft();draft.name='Runtime queue';draft.items[0].message='Runtime {iteration}';const created=await client.create(draft);assert.equal((await client.list()).length,1);const loaded=await client.hydrate(created.queue.id);const edit=queueDraftFrom(loaded);edit.items[0].message='Changed {iteration}';const updated=await client.update(edit);const duplicate=await client.duplicate(updated);await client.delete(updated);assert.notEqual(duplicate.queue.id,updated.queue.id);assert.equal(invalidations,4);});

test('STEP-12 hydration resolves current Template revision and protects referenced Template/Queue deletion',async()=>{const{queues,templates,presets}=await harness();let queue=await queues.create(ids.queue,input);await templates.update(ids.template,1,{name:'Latest',body:'Latest {iteration}/{total}',enabled:true});queue=await queues.hydrate(ids.queue);assert.equal(queue.resolvedItems[1].templateRevision,2);assert.match(queue.resolvedItems[1].content,/Latest/);await assert.rejects(()=>templates.delete(ids.template,2),/referenced/);const preset=await presets.create(ids.preset,{name:'Queue preset',mode:'queue',templateId:null,queueId:ids.queue,iterationCount:1,delaySeconds:8,autoContinue:true,autoScroll:true,preventDiscard:true});const copy=runWorkingCopyFromPreset(await presets.hydrate(preset.id));assert.equal(copy.mode,'queue');assert.equal(copy.queueId,ids.queue);await assert.rejects(()=>queues.delete(ids.queue,queue.queue.revision),/referenced by a preset/);});

test('STEP-12 QueueMessageSource walks frozen order, renders bounded variables, and exposes per-item delay override',()=>{const source=new QueueMessageSource([{id:ids.item1,position:0,source:'literal',templateId:null,templateRevision:null,content:'One {iteration}/{total}',delayAfterSeconds:11},{id:ids.item2,position:1,source:'template',templateId:ids.template,templateRevision:2,content:'Two {remaining}',delayAfterSeconds:null}]);const first=source.next({iteration:1,total:2,remaining:1,timestamp:'2026-08-24T00:00:00Z'});assert.equal(first.content,'One 1/2');assert.equal(first.delayAfterSeconds,11);assert.equal(source.next({iteration:2,total:2,remaining:0,timestamp:'2026-08-24T00:00:00Z'}).content,'Two 0');assert.equal(source.next({iteration:3,total:2,remaining:0,timestamp:'2026-08-24T00:00:00Z'}),null);});

class FakeWaiter{async waitUntilIdle(){return{assistantFingerprint:'af2:11111111111111111111111111111111'}}async waitForResponse(){return{assistantFingerprint:'af2:22222222222222222222222222222222'}}}class FakeClient{sends=[];async send(tabId,message,baseline){this.sends.push({tabId,message,baseline})}async scrollToBottom(){}async continueResponse(){}}class FakeScheduler{pending=new Map();async schedule(runId,g,dueAt,cb){this.pending.set(runId,{g,dueAt,cb});return'short_timer'}async cancel(id){this.pending.delete(id)}fire(id){const x=this.pending.get(id);this.pending.delete(id);x?.cb()}}
async function eventually(fn){for(let i=0;i<200;i++){const v=await fn();if(v)return v;await new Promise(r=>setTimeout(r,5))}throw Error('not reached')}

test('STEP-12 same durable coordinator executes Queue mode and honors item delay override without duplicate orchestration',async()=>{const{repositories,queues}=await harness();const q=await queues.create(ids.queue,input);let tick=0;const repo=new DurableRunRepository(repositories,{now:()=>new Date(Date.parse('2026-08-24T04:10:00+08:00')+tick++*1000).toISOString(),id:()=>crypto.randomUUID()});const manager=new DurableRunManager(repo);let run=(await manager.create({targetTabId:9,targetWindowId:1,commandId:crypto.randomUUID(),mode:'queue',queueId:q.queue.id,queueRevision:q.queue.revision,queueItems:q.resolvedItems,delaySeconds:5,autoContinue:true,autoScroll:false,preventDiscard:false})).snapshot;run=(await manager.start(run.id,run.generation,crypto.randomUUID())).snapshot;const client=new FakeClient(),scheduler=new FakeScheduler(),coordinator=new RepeatRunCoordinator(manager,client,new FakeWaiter(),scheduler);coordinator.activate(run);const waiting=await eventually(async()=>{const x=await manager.get(run.id);return x?.lifecycleState==='waiting_delay'?x:null});assert.equal(waiting.execution.mode,'queue');assert.equal(client.sends[0].message,'Literal 1/2');const delta=(Date.parse(waiting.execution.nextDueAt)-Date.parse(waiting.updatedAt))/1000;assert.ok(delta>=8&&delta<=12);scheduler.fire(run.id);const done=await eventually(async()=>{const x=await manager.get(run.id);return x?.lifecycleState==='completed'?x:null});assert.equal(done.execution.completedIterations,2);assert.match(client.sends[1].message,/Template 2\/2/);});

test('STEP-12 runtime resolves Queue server-side and SidePanel startQueue creates a frozen queue run snapshot',async()=>{const{repositories,queues}=await harness();await queues.create(ids.queue,input);let tick=0;const repo=new DurableRunRepository(repositories,{now:()=>new Date(Date.parse('2026-08-24T04:20:00+08:00')+tick++*1000).toISOString(),id:()=>crypto.randomUUID()});const manager=new DurableRunManager(repo);const execution={activate(){},async cancel(){}};const server=new RunRuntimeServer(async()=>manager,async()=>execution,async()=>queues);const client=new SidePanelOperationalClient({sendMessage:async req=>{if(req.operation==='tabs.bind')return createSuccessResponse(req,{schemaVersion:TAB_REGISTRY_SCHEMA_VERSION,revision:1,targets:[],binding:null,lastTermination:null});return await server.handle(req)}});const run=await client.startQueue({targetTabId:4,targetWindowId:2,queueId:ids.queue,delaySeconds:6,autoContinue:true,autoScroll:false,preventDiscard:true});assert.equal(run.execution.mode,'queue');assert.equal(run.execution.queueId,ids.queue);assert.equal(run.execution.items.length,2);});

test('STEP-12 queue working copy preserves stable identities with explicit move controls and stale detection',async()=>{const{queues}=await harness();const q=await queues.create(ids.queue,input);const draft=queueDraftFrom(q);assert.equal(isQueueDraftDirty(draft,q),false);moveQueueItem(draft,1,-1);assert.deepEqual(draft.items.map(i=>i.sourceId),[ids.item2,ids.item1]);assert.equal(isQueueDraftDirty(draft,q),true);assert.equal(isQueueDraftStale(draft,{...q.queue,revision:2}),true);const blank=blankQueueDraft();assert.equal(blank.items.length,1);});

test('STEP-12 Side Panel implements team-standard Queue lifecycle and explicit non-drag ordering plus Run mode',async()=>{const app=await text('entrypoints/sidepanel/App.vue');for(const marker of ['queue-select','beginNewQueue','saveQueueAs','updateQueue','resetQueue','duplicateQueue','deleteQueue','moveQueueDraftItem','removeQueueDraftItem'])assert.match(app,new RegExp(marker));for(const marker of ['run-mode','run-queue','startQueue'])assert.match(app,new RegExp(marker));assert.match(app,/Move Up|moveUp/);assert.match(app,/Move Down|moveDown/);assert.doesNotMatch(app,/draggable="true"/);assert.match(app,/structured-list/);});

test('STEP-12 queue invalidation, localization, physical schema, and permission floor stay bounded',async()=>{const[types,panel,bg,router,locale,schema,versions,config,coordinator]=await Promise.all(['src/control-plane/types.ts','src/control-plane/panel-client.ts','entrypoints/background.ts','src/runtime/message-router.ts','public/_locales/en/messages.json','src/persistence/schema.ts','src/persistence/versions.ts','wxt.config.ts','src/runs/repeat-coordinator.ts'].map(text));assert.match(types,/queue_changed/);assert.match(panel,/queue_changed/);assert.match(bg,/QueueRuntimeServer/);assert.match(bg,/ports\.broadcast\('queue_changed'\)/);assert.match(router,/QUEUE_RUNTIME_OPERATIONS/);const messages=JSON.parse(locale);for(const key of ['queueLibrary','queueWorkingCopy','moveUp','moveDown','remove','addQueueItem','runMode','runQueue'])assert.equal(typeof messages[key]?.message,'string');assert.match(schema,/name: 'queueItems'/);assert.match(versions,/PHYSICAL_DB_VERSION\s*=\s*1/);assert.match(config,/permissions:\s*\[['"]sidePanel['"],\s*['"]storage['"],\s*['"]alarms['"]\]/);assert.match(coordinator,/sourceFor\(run/);assert.equal((coordinator.match(/waitForResponse/g)??[]).length,1);});
