import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
import { ApplicationRepositories, NamespacedChromeStorage, PERSISTENCE_STORES } from '../src/persistence/index.ts';
import { TemplateService } from '../src/templates/index.ts';
import { PresetService } from '../src/presets/index.ts';
import { QueueService } from '../src/queues/index.ts';
import { SettingsService } from '../src/settings/index.ts';
import { DurableRunManager, DurableRunRepository } from '../src/runs/index.ts';
import { PortabilityService, requirePortableEnvelope, PORTABLE_FORMAT_VERSION, PORTABLE_IMPORT_ADAPTERS } from '../src/portability/index.ts';
import { PortabilityRuntimeServer } from '../src/runtime/index.ts';
import { SidePanelPortabilityClient, parsePortableJson } from '../src/ui/portability-workspace.ts';

const clone=v=>structuredClone(v);const keyFor=(s,v)=>s==='metadata'?v.key:v.id;
function matchesIndex(store,index,value,query){if(query===undefined)return true;if(store==='queueItems'&&index==='byQueueId')return value.queueId===query;if(store==='runEvents'&&index==='byRunId')return value.runId===query;if(store==='runEvents'&&index==='byRunSequence')return Array.isArray(query)&&value.runId===query[0]&&value.sequence===query[1];return value[index==='byUpdatedAt'?'updatedAt':index==='byOccurredAt'?'occurredAt':'id']===query;}
class MemoryDriver{state=new Map(PERSISTENCE_STORES.map(n=>[n,new Map()]));failNextWrite=false;async transaction(stores,mode,work){if(mode==='readwrite'&&this.failNextWrite){this.failNextWrite=false;throw Error('injected persistence failure')}const before=new Map([...this.state].map(([n,v])=>[n,new Map([...v].map(([k,x])=>[k,clone(x)]))]));const port={store:(name)=>({get:async k=>{const v=this.state.get(name).get(k);return v===undefined?undefined:clone(v)},getAll:async()=>[...this.state.get(name).values()].map(clone),getAllByIndex:async(i,q)=>[...this.state.get(name).values()].filter(v=>matchesIndex(name,i,v,q)).map(clone),put:async v=>{if(mode!=='readwrite')throw Error('readonly');this.state.get(name).set(keyFor(name,v),clone(v))},delete:async k=>{if(mode!=='readwrite')throw Error('readonly');this.state.get(name).delete(k)}})};try{return await work(port)}catch(e){this.state=before;throw e}}close(){}}
class MemoryStorageArea{values={};async get(keys){if(keys==null)return clone(this.values);const list=Array.isArray(keys)?keys:[keys];return Object.fromEntries(list.filter(k=>k in this.values).map(k=>[k,clone(this.values[k])]))}async set(items){Object.assign(this.values,clone(items))}async remove(keys){for(const k of Array.isArray(keys)?keys:[keys])delete this.values[k]}}
const ids={template:'11111111-1111-4111-8111-111111111111',preset:'22222222-2222-4222-8222-222222222222',queue:'33333333-3333-4333-8333-333333333333',item:'44444444-4444-4444-8444-444444444444'};
function harness(appVersion='0.0.14'){const driver=new MemoryDriver();const repositories=new ApplicationRepositories(driver);const area=new MemoryStorageArea();let tick=0;const now=()=>new Date(Date.parse('2026-08-24T05:00:00+08:00')+tick++*1000).toISOString();const settings=new SettingsService(new NamespacedChromeStorage(area,'sync'),now);const portability=new PortabilityService(repositories,settings,appVersion,now);return{driver,repositories,area,settings,portability,templates:new TemplateService(repositories,now),presets:new PresetService(repositories,now),queues:new QueueService(repositories,now,()=>crypto.randomUUID()),now};}
async function seed(h,{terminal=true}={}){await h.templates.create(ids.template,{name:'Continue',body:'Continue {iteration}/{total}',enabled:true});await h.queues.create(ids.queue,{name:'Q',items:[{id:ids.item,message:null,templateId:ids.template,enabled:true,delayAfterSeconds:null}]});await h.presets.create(ids.preset,{name:'P',mode:'repeat',templateId:ids.template,queueId:null,iterationCount:3,delaySeconds:7,autoContinue:true,autoScroll:true,preventDiscard:true});const current=await h.settings.get();await h.settings.update(current.revision,{defaultPresetId:ids.preset,defaultDelaySeconds:9,defaultAutoContinue:true,defaultAutoScroll:false,defaultPreventDiscard:true,recoveryPolicy:'pause',historyLimit:25});let tick=0;const manager=new DurableRunManager(new DurableRunRepository(h.repositories,{now:()=>new Date(Date.parse('2026-08-24T05:30:00+08:00')+tick++*1000).toISOString(),id:()=>crypto.randomUUID()}));let run=(await manager.create({targetTabId:7,targetWindowId:1,commandId:crypto.randomUUID(),messageTemplate:'PRIVATE {iteration}',totalIterations:1,delaySeconds:5,autoContinue:true,autoScroll:true,preventDiscard:true})).snapshot;if(terminal)run=(await manager.stop(run.id,run.generation,crypto.randomUUID())).snapshot;return{manager,run};}

test('STEP-14 configuration export is portable v1 and excludes run history by default',async()=>{const h=harness();await seed(h);const out=await h.portability.export('configuration');assert.equal(out.product,'chatgpt-iterator');assert.equal(out.formatVersion,1);assert.equal(out.kind,'configuration');assert.equal(out.data.templates.length,1);assert.equal(out.data.queues[0].items.length,1);assert.equal(out.data.settings.defaultPresetId,ids.preset);assert.equal('history' in out.data,false);assert.equal(JSON.stringify(out).includes('PRIVATE'),false);});

test('STEP-14 full backup includes terminal history/events only and is explicit sensitive scope',async()=>{const h=harness();await seed(h,{terminal:true});const out=await h.portability.export('full_backup');assert.equal(out.kind,'full_backup');assert.ok((out.data.history?.length??0)>=1);assert.ok(out.data.history.every(x=>['completed','failed','stopped'].includes(x.run.lifecycleState)));const preview=await h.portability.preview(out,'merge');assert.ok(preview.warnings.some(x=>/sensitive/i.test(x)));});

test('STEP-14 round-trip replace_all preserves stable ids/references/settings across app versions',async()=>{const source=harness('0.0.13');await seed(source);const exported=await source.portability.export('configuration');const dest=harness('0.0.14');const preview=await dest.portability.preview(exported,'replace_all');await dest.portability.apply(exported,'replace_all',preview.planFingerprint);const again=await dest.portability.export('configuration');assert.deepEqual(again.data.templates.map(x=>x.id),[ids.template]);assert.equal(again.data.presets[0].templateId,ids.template);assert.equal(again.data.queues[0].items[0].templateId,ids.template);assert.equal(again.data.settings.defaultPresetId,ids.preset);});

test('STEP-14 merge keeps existing id collisions while replace_imported overwrites imported ids',async()=>{const source=harness();await seed(source);const exported=await source.portability.export('configuration');const dest=harness();await dest.templates.create(ids.template,{name:'Local',body:'LOCAL',enabled:true});let p=await dest.portability.preview(exported,'merge');assert.equal(p.conflicts.templates,1);await dest.portability.apply(exported,'merge',p.planFingerprint);assert.equal((await dest.templates.get(ids.template)).body,'LOCAL');p=await dest.portability.preview(exported,'replace_imported');await dest.portability.apply(exported,'replace_imported',p.planFingerprint);assert.match((await dest.templates.get(ids.template)).body,/Continue/);});

test('STEP-14 failed reference validation is preview-only and leaves durable state untouched',async()=>{const h=harness();await seed(h);const envelope=await h.portability.export('configuration');const broken=clone(envelope);broken.data.presets[0].templateId='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';await assert.rejects(()=>h.portability.preview(broken,'replace_all'),/missing template/);assert.equal((await h.templates.get(ids.template)).name,'Continue');});

test('STEP-14 stale preview fingerprint prevents mutation after local data changes',async()=>{const source=harness();await seed(source);const envelope=await source.portability.export('configuration');const dest=harness();const preview=await dest.portability.preview(envelope,'merge');await dest.templates.create('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',{name:'Later',body:'Later',enabled:true});await assert.rejects(()=>dest.portability.apply(envelope,'merge',preview.planFingerprint),/changed after import preview/);assert.equal((await dest.templates.get('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa')).name,'Later');});

test('STEP-14 injected IndexedDB failure compensates Settings back to the exact prior snapshot',async()=>{const source=harness();await seed(source);const envelope=await source.portability.export('configuration');const dest=harness();const before=await dest.settings.get();const preview=await dest.portability.preview(envelope,'replace_all');dest.driver.failNextWrite=true;await assert.rejects(()=>dest.portability.apply(envelope,'replace_all',preview.planFingerprint),/injected persistence failure/);assert.deepEqual(await dest.settings.get(),before);assert.equal((await dest.templates.list()).length,0);});

test('STEP-14 full-backup replace_all restores terminal history but preserves active local runs',async()=>{const source=harness();await seed(source,{terminal:true});const backup=await source.portability.export('full_backup');const dest=harness();const {run:active}=await seed(dest,{terminal:false});const p=await dest.portability.preview(backup,'replace_all');await dest.portability.apply(backup,'replace_all',p.planFingerprint);const rows=await dest.repositories.readonly(['runs'],async tx=>await tx.repository('runs').list());assert.ok(rows.some(x=>x.id===active.id));assert.ok(rows.some(x=>x.id===backup.data.history[0].run.id));});

test('STEP-14 explicit adapter registry supports v1 and rejects unknown older formats instead of guessing',()=>{assert.equal(PORTABLE_FORMAT_VERSION,1);assert.equal(PORTABLE_IMPORT_ADAPTERS.has(1),true);const raw={product:'chatgpt-iterator',formatVersion:0,kind:'configuration',appVersion:'0.0.0',exportedAt:'2026-08-24T00:00:00Z',data:{}};assert.throws(()=>requirePortableEnvelope(raw),/unsupported portable formatVersion/);assert.throws(()=>parsePortableJson(JSON.stringify(raw)),/unsupported portable formatVersion/);});

test('STEP-14 background runtime/client and Settings Data UI enforce preview-before-apply modes without schema or permission churn',async()=>{const h=harness();await seed(h);const server=new PortabilityRuntimeServer(async()=>h.portability);const client=new SidePanelPortabilityClient({sendMessage:async req=>await server.handle(req)});const envelope=await client.export('configuration');const p=await client.preview(envelope,'merge');assert.equal(p.mode,'merge');const app=await readFile(new URL('../entrypoints/sidepanel/App.vue',import.meta.url),'utf8');for(const marker of ['exportPortable','selectPortableFile','previewPortableImport','applyPortableImport','replace_imported','replace_all'])assert.match(app,new RegExp(marker));const versions=await readFile(new URL('../src/persistence/versions.ts',import.meta.url),'utf8');const config=await readFile(new URL('../wxt.config.ts',import.meta.url),'utf8');assert.match(versions,/PHYSICAL_DB_VERSION\s*=\s*1/);assert.match(versions,/EXPORT_FORMAT_VERSION\s*=\s*1/);assert.match(config,/permissions:\s*\[['"]sidePanel['"],\s*['"]storage['"],\s*['"]alarms['"]\]/);});
