import { ContractError, ERROR_CODES, createRequest, requireMessageEnvelope } from '../core/index.ts';
import type { JsonObject, MessageIntent } from '../core/types.ts';
import { requireQueueWriteInput } from '../queues/model.ts';
import { QUEUE_RUNTIME_OPERATIONS, type QueueHydration, type QueueReferenceCatalog, type QueueSnapshot } from '../queues/types.ts';

export interface QueuePanelRuntimeLike { sendMessage(message: unknown): Promise<unknown>; }
export interface QueueItemDraft { localKey:string; sourceId:string|null; kind:'literal'|'template'; message:string; templateId:string|null; enabled:boolean; delayAfterSeconds:number|null; }
export interface QueueDraft { readonly sourceId:string|null; readonly sourceRevision:number|null; name:string; items:QueueItemDraft[]; }

export function blankQueueItem(kind:'literal'|'template'='literal'):QueueItemDraft{return {localKey:crypto.randomUUID(),sourceId:null,kind,message:'',templateId:null,enabled:true,delayAfterSeconds:null};}
export function blankQueueDraft():QueueDraft{return {sourceId:null,sourceRevision:null,name:'',items:[blankQueueItem()]};}
export function queueDraftFrom(source:QueueHydration):QueueDraft{return {sourceId:source.queue.id,sourceRevision:source.queue.revision,name:source.queue.name,items:source.items.map(i=>({localKey:i.id,sourceId:i.id,kind:i.templateId===null?'literal':'template',message:i.message??'',templateId:i.templateId,enabled:i.enabled,delayAfterSeconds:i.delayAfterSeconds}))};}
function comparable(draft:QueueDraft){return {name:draft.name,items:draft.items.map(i=>({id:i.sourceId,kind:i.kind,message:i.kind==='literal'?i.message:'',templateId:i.kind==='template'?i.templateId:null,enabled:i.enabled,delayAfterSeconds:i.delayAfterSeconds}))};}
export function isQueueDraftDirty(draft:QueueDraft,base:QueueHydration|undefined):boolean{return base===undefined?(draft.name.trim().length>0||draft.items.some(i=>i.message||i.templateId||!i.enabled||i.delayAfterSeconds!==null)):JSON.stringify(comparable(draft))!==JSON.stringify(comparable(queueDraftFrom(base)));}
export function isQueueDraftStale(draft:QueueDraft,latest:QueueSnapshot|undefined):boolean{return draft.sourceId!==null&&draft.sourceRevision!==null&&(latest===undefined||latest.id!==draft.sourceId||latest.revision!==draft.sourceRevision);}
export function normalizeQueueItem(item:QueueItemDraft):void{if(item.kind==='literal')item.templateId=null;else item.message='';}
export function moveQueueItem(draft:QueueDraft,index:number,direction:-1|1):void{const target=index+direction;if(index<0||target<0||index>=draft.items.length||target>=draft.items.length)return;const [item]=draft.items.splice(index,1);draft.items.splice(target,0,item!);}
export function removeQueueItem(draft:QueueDraft,index:number):void{if(draft.items.length<=1)return;draft.items.splice(index,1);}
export function validateQueueDraft(draft:QueueDraft):void{requireQueueWriteInput({name:draft.name,items:draft.items.map(i=>({id:i.sourceId,message:i.kind==='literal'?i.message:null,templateId:i.kind==='template'?i.templateId:null,enabled:i.enabled,delayAfterSeconds:i.delayAfterSeconds}))});}
function payload(d:QueueDraft):JsonObject{validateQueueDraft(d);return {name:d.name,items:d.items.map(i=>({id:i.sourceId,message:i.kind==='literal'?i.message:null,templateId:i.kind==='template'?i.templateId:null,enabled:i.enabled,delayAfterSeconds:i.delayAfterSeconds}))};}
function hydration(v:unknown):QueueHydration{if(v===null||Array.isArray(v)||typeof v!=='object')throw new ContractError(ERROR_CODES.invalidMessage,'queue hydration must be an object');const c=v as Record<string,unknown>;if(c.schemaVersion!==1||c.queue===null||!Array.isArray(c.items)||!Array.isArray(c.resolvedItems))throw new ContractError(ERROR_CODES.invalidMessage,'invalid queue hydration');return c as unknown as QueueHydration;}
function list(v:unknown):QueueSnapshot[]{if(!Array.isArray(v))throw new ContractError(ERROR_CODES.invalidMessage,'queue list response must be an array');return v as QueueSnapshot[];}
function refs(v:unknown):QueueReferenceCatalog{if(v===null||Array.isArray(v)||typeof v!=='object'||!Array.isArray((v as Record<string,unknown>).templates))throw new ContractError(ERROR_CODES.invalidMessage,'invalid queue references');return v as QueueReferenceCatalog;}
export class SidePanelQueueClient{readonly #runtime:QueuePanelRuntimeLike;#requestSequence=0;constructor(runtime:QueuePanelRuntimeLike){this.#runtime=runtime;}async list(){return list(await this.#request('query',QUEUE_RUNTIME_OPERATIONS.list,{}));}async references(){return refs(await this.#request('query',QUEUE_RUNTIME_OPERATIONS.references,{}));}async hydrate(queueId:string){return hydration(await this.#request('query',QUEUE_RUNTIME_OPERATIONS.hydrate,{queueId}));}async create(d:QueueDraft){return hydration(await this.#request('command',QUEUE_RUNTIME_OPERATIONS.create,payload(d)));}async update(d:QueueDraft){if(d.sourceId===null||d.sourceRevision===null)throw new ContractError(ERROR_CODES.invalidMessage,'load a queue before updating');return hydration(await this.#request('command',QUEUE_RUNTIME_OPERATIONS.update,{queueId:d.sourceId,expectedRevision:d.sourceRevision,...payload(d)}));}async duplicate(source:QueueHydration,name?:string){return hydration(await this.#request('command',QUEUE_RUNTIME_OPERATIONS.duplicate,{queueId:source.queue.id,expectedRevision:source.queue.revision,...(name===undefined?{}:{name})}));}async delete(source:QueueHydration){await this.#request('command',QUEUE_RUNTIME_OPERATIONS.delete,{queueId:source.queue.id,expectedRevision:source.queue.revision});}async #request(intent:MessageIntent,operation:string,payload:JsonObject):Promise<unknown>{const request=createRequest({requestSequence:++this.#requestSequence,intent,source:'sidepanel',target:'background',operation,payload});const response=requireMessageEnvelope(await this.#runtime.sendMessage(request));if(response.kind!=='response'||response.requestId!==request.requestId||response.requestSequence!==request.requestSequence||response.operation!==operation)throw new ContractError(ERROR_CODES.invalidMessage,'queue response correlation failed');if(!response.outcome.ok)throw new ContractError(response.outcome.error.code,response.outcome.error.message,response.outcome.error.details);return response.outcome.value;}}
